-- Flow tabloları (mevcut SQL'e göre)

-- flow_actions tablosu
CREATE TABLE public.flow_actions (
  id bigint generated by default as identity not null,
  description text null,
  action_type text not null,
  parameters jsonb null,
  created_at timestamp with time zone null default now(),
  constraint flow_actions_pkey primary key (id)
) TABLESPACE pg_default;

-- flow_questions tablosu
CREATE TABLE public.flow_questions (
  id bigint generated by default as identity not null,
  slug text not null,
  is_start_question boolean null default false,
  created_at timestamp with time zone null default now(),
  constraint flow_questions_pkey primary key (id),
  constraint flow_questions_slug_key unique (slug)
) TABLESPACE pg_default;

-- flow_question_translations tablosu
CREATE TABLE public.flow_question_translations (
  id bigint generated by default as identity not null,
  question_id bigint not null,
  language_code character varying(5) not null,
  text text not null,
  constraint flow_question_translations_pkey primary key (id),
  constraint flow_question_translations_question_id_language_code_key unique (question_id, language_code),
  constraint flow_question_translations_question_id_fkey foreign KEY (question_id) references flow_questions (id) on delete CASCADE
) TABLESPACE pg_default;

-- flow_answers tablosu
CREATE TABLE public.flow_answers (
  id bigint generated by default as identity not null,
  question_id bigint not null,
  next_question_id bigint null,
  action_id bigint null,
  created_at timestamp with time zone null default now(),
  constraint flow_answers_pkey primary key (id),
  constraint flow_answers_action_id_fkey foreign KEY (action_id) references flow_actions (id) on delete set null,
  constraint flow_answers_next_question_id_fkey foreign KEY (next_question_id) references flow_questions (id) on delete set null,
  constraint flow_answers_question_id_fkey foreign KEY (question_id) references flow_questions (id) on delete CASCADE,
  constraint answer_must_lead_somewhere check (
    (
      (
        (next_question_id is not null)
        and (action_id is null)
      )
      or (
        (next_question_id is null)
        and (action_id is not null)
      )
    )
  )
) TABLESPACE pg_default;

-- flow_answer_translations tablosu
CREATE TABLE public.flow_answer_translations (
  id bigint generated by default as identity not null,
  answer_id bigint not null,
  language_code character varying(5) not null,
  text text not null,
  constraint flow_answer_translations_pkey primary key (id),
  constraint flow_answer_translations_answer_id_language_code_key unique (answer_id, language_code),
  constraint flow_answer_translations_answer_id_fkey foreign KEY (answer_id) references flow_answers (id) on delete CASCADE
) TABLESPACE pg_default;

-- RLS politikaları
ALTER TABLE flow_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_question_translations ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE flow_answer_translations ENABLE ROW LEVEL SECURITY;

-- Authenticated users için politikalar
CREATE POLICY "Allow authenticated users to manage flow_actions" ON flow_actions
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to manage flow_questions" ON flow_questions
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to manage flow_question_translations" ON flow_question_translations
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to manage flow_answers" ON flow_answers
    FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to manage flow_answer_translations" ON flow_answer_translations
    FOR ALL USING (auth.role() = 'authenticated');

-- Örnek veriler
INSERT INTO flow_actions (description, action_type, parameters) VALUES 
('Rastgele yemek tarifi getir', 'FETCH_RANDOM_RECIPE', '{"table_name": "food_recipes"}'),
('Özel mesaj göster', 'SHOW_CUSTOM_MESSAGE', '{"message": "Teşekkürler!"}');

INSERT INTO flow_questions (slug, is_start_question) VALUES 
('welcome_question', true),
('preference_question', false);

INSERT INTO flow_question_translations (question_id, language_code, text) VALUES 
(1, 'tr', 'Merhaba! Size nasıl yardımcı olabilirim?'),
(1, 'en', 'Hello! How can I help you?'),
(2, 'tr', 'Hangi türde yardım istiyorsunuz?'),
(2, 'en', 'What kind of help do you want?');

INSERT INTO flow_answers (question_id, next_question_id, action_id) VALUES 
(1, 2, NULL),
(2, NULL, 1);

INSERT INTO flow_answer_translations (answer_id, language_code, text) VALUES 
(1, 'tr', 'Yardım almak istiyorum'),
(1, 'en', 'I want to get help'),
(2, 'tr', 'Yemek tarifi istiyorum'),
(2, 'en', 'I want a recipe');
