create table public.categories (
  category_name text not null,
  description text null,
  thumbnail text null,
  updated_at timestamp with time zone null default now(),
  created_at timestamp with time zone not null default now(),
  constraint categories_pkey primary key (category_name)
) TABLESPACE pg_default;

create table public.daily_recommendations (
  id bigint generated by default as identity not null,
  date date null,
  created_at timestamp with time zone not null default now(),
  metadata jsonb null,
  updated_at timestamp with time zone null default now(),
  menu jsonb null,
  constraint daily_recomendation_pkey primary key (id),
  constraint daily_recommendations_date_key unique (date)
) TABLESPACE pg_default;

create table public.items (
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null default now(),
  title text null,
  description text null,
  score smallint null,
  icon text null,
  time_type text null,
  metadata jsonb null,
  tags text[] null,
  id text not null,
  category text null,
  constraint item_pkey primary key (id),
  constraint item_category_fkey foreign KEY (category) references categories (category_name)
) TABLESPACE pg_default;

